# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180618_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
