# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='reply',
            field=models.TextField(blank=True),
        ),
    ]
